export type Experience = { slug: string; date: string; title: string; place: string; detail: string; did: string[]; learned: string[] }

export const experiences: Experience[] = [
  { slug: 'amigos-foundation', date: 'Feb 2025 — Jul 2025', title: 'Web & Technology Volunteer', place: 'Amigos Foundation / NGO', detail: 'Five months of building useful digital touchpoints for a mission-led organisation.', did: ['Supported web content and digital communication for the foundation.', 'Improved clarity and consistency across online information.', 'Worked with a small team where initiative mattered more than hierarchy.'], learned: ['Technology can create trust when it is clear and accessible.', 'Mission-led work rewards patience, empathy, and practical ownership.', 'Small improvements compound when they serve real people.'] },
  { slug: 'ieee-web-lead', date: '2025 — now', title: 'IEEE Web Member → Web Lead', place: 'Rajalakshmi Engineering College / IEEE', detail: 'Promoted from web member to web lead by turning reliable execution into team-wide momentum.', did: ['Started as a web member building responsive event experiences.', 'Led the web direction for IEEE platforms, hackathons, and registrations.', 'Reviewed work, coordinated delivery, and raised the quality bar for the team.'], learned: ['Leadership is an extension of craft and communication.', 'A promotion is earned by making the whole team faster and clearer.', 'Systems scale when knowledge is shared, not guarded.'] },
  { slug: 'frontend-internship', date: '2024', title: 'Frontend Engineering Intern', place: 'Product team / interface systems', detail: 'Built responsive interfaces and translated product ideas into useful, polished flows.', did: ['Shipped reusable React components and responsive layouts.', 'Worked with APIs, state, and interaction patterns across product surfaces.', 'Collaborated with teammates to turn rough concepts into launchable work.'], learned: ['How to make systems consistent without making them feel static.', 'How to communicate technical trade-offs clearly.', 'How tiny interaction details shape user trust.'] },
  { slug: 'cyber-security', date: '2023 — now', title: 'Cyber Security Student', place: 'Information security / continuous research', detail: 'Exploring secure systems, threat thinking, and the discipline behind resilient digital products.', did: ['Studied foundational security concepts, networks, and vulnerabilities.', 'Practiced breaking down risk into observable, testable problems.', 'Connected security thinking with frontend and product decisions.'], learned: ['Security is a product quality, not a final checklist.', 'Curiosity and careful documentation are powerful technical tools.', 'The best interfaces make complex risk easier to understand.'] },
  { slug: 'project-builder', date: '2022 — now', title: 'Independent Project Builder', place: 'Mani Labs / self-directed work', detail: 'A personal lab for building ambitious experiments where code, visual design, and storytelling meet.', did: ['Designed and developed FleetSensor, ThinkIt, and Xyntra concepts.', 'Created end-to-end prototypes from product narrative to interaction.', 'Used projects as a way to test new tools and sharpen execution.'], learned: ['A strong concept becomes memorable through restraint.', 'Shipping small, coherent experiments compounds quickly.', 'The next level is always one more thoughtful detail.'] },
]
